version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql